from typing import Protocol


class FileStorage(Protocol):
    async def save(self, relative_path: str, content: bytes) -> str: ...
    async def delete(self, relative_path: str) -> None: ...
    async def exists(self, relative_path: str) -> bool: ...
